[package]
name = "rutter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version = "0.5.0-rc.1", features= ["json"]}
rocket_db_pools = {version = "0.1.0-rc", features = ["deadpool_redis"]}
redis = "0.21.5"

[patch.crates-io]
rocket = { git = "https://github.com/SergioBenitez/Rocket"}
rocket_db_pools= {  git = "https://github.com/SergioBenitez/Rocket"}
