[debug.databases.redis]
url = "redis://localhost/"

[release.databases.redis]
url = "redis://redis"

[release]
address = "0.0.0.0"
port = 8000
log_level = "off"

[debug]
address = "127.0.0.1"
port = 8000
